name: brain_box
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+14

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  go_router: ^12.1.0
  google_sign_in: ^6.1.6
  flutter_native_splash: ^2.3.5
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  auto_size_text: ^3.0.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  delayed_widget: ^1.1.2
  webview_flutter: ^4.4.2
  flutter_windowmanager:
  google_mobile_ads:
  in_app_purchase: ^3.1.11
  get_it: ^7.6.4
  dio: ^5.3.4
  formz: ^0.6.1
  permission_handler: ^11.0.0
  flutter_rating_bar: ^4.0.1
  device_info_plus: ^9.1.1
  hive: ^2.2.3
  path_provider: ^2.1.1
  hive_flutter: ^1.1.0
  json_annotation:
  flutter_jailbreak_detection:
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^16.2.0
  flutter_timezone: ^1.0.8
  shimmer: ^3.0.0
  easy_rich_text: ^2.1.0
  in_app_update: ^4.2.2
  package_info: ^2.0.2
  in_app_review: ^2.0.8
  url_launcher: ^6.2.2
  freerasp: ^6.3.0
  audioplayers: ^5.2.1
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7
  hive_generator:
  json_serializable:


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - assets/images/
    - assets/translations/
