name: brain_box
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+17

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  go_router: ^13.0.1
  google_sign_in: ^6.2.1
  flutter_native_splash: ^2.3.9
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  auto_size_text: ^3.0.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  delayed_widget: ^1.1.2
  webview_flutter: ^4.4.4
  flutter_windowmanager:
  google_mobile_ads:
  in_app_purchase: ^3.1.13
  get_it: ^7.6.6
  dio: ^5.4.0
  formz: ^0.6.1
  permission_handler: ^11.1.0
  flutter_rating_bar: ^4.0.1
  device_info_plus: ^9.1.1
  hive: ^2.2.3
  path_provider: ^2.1.2
  hive_flutter: ^1.1.0
  json_annotation:
  flutter_jailbreak_detection:
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^16.3.0
  flutter_timezone: ^1.0.8
  shimmer: ^3.0.0
  easy_rich_text: ^2.1.0
  in_app_update: ^4.2.2
  package_info: ^2.0.2
  in_app_review: ^2.0.8
  url_launcher: ^6.2.3
  freerasp: ^6.4.0
  audioplayers: ^5.2.1
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  flutter_tts: ^3.8.5
  flashy_tab_bar2: ^0.0.6
  gap: ^3.0.1
  awesome_extensions: ^2.0.11
  flutter_linkify: ^6.0.0
  uuid: ^4.3.3
  fluttertoast: ^8.2.4
  firebase_messaging: ^14.7.10
  overlay_support: ^2.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  dartz: ^0.10.1
  bloc_concurrency: ^0.2.3
  stream_transform: ^2.1.0
  sign_in_with_apple: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - assets/images/
    - assets/translations/
